FROM ubuntu:xenial
RUN apt-get update
RUN apt-get install -y python3 python3-dev python3-pip git net-tools
RUN git clone https://github.com/bashwork/pymodbus
WORKDIR /pymodbus
RUN git checkout --track origin/python3
RUN python3 setup.py install
RUN pip3 install attrs Automat constantly incremental ipaddress netaddr netifaces pycrypto pyserial six Twisted zope.interface --user
